package constants

var CountryTldList = map[string]map[string]string{
	"": {"sub": "gate", "host": "smartproxy.com:10000", "tld": "com"},
	"united states": {
		"sub":  "us",
		"host": "smartproxy.com:10000",
		"tld":  "com",
	},
	"europe": {
		"sub":  "eu",
		"host": "smartproxy.com:10000",
		"tld":  "co.uk",
	},
	"uae":      {"sub": "ae", "host": "smartproxy.com:20000", "tld": "ae"},
	"malaysia": {"sub": "my", "host": "smartproxy.com:30000", "tld": "com.my"},
	"philippines": {
		"sub":  "ph",
		"host": "smartproxy.com:40000",
		"tld":  "com.ph",
	},
	"india": {
		"sub":  "in",
		"host": "smartproxy.com:10000",
		"tld":  "google.co.in",
	},
	"taiwan":     {"sub": "tw", "host": "smartproxy.com:20000", "tld": "com.tw"},
	"japan":      {"sub": "jp", "host": "smartproxy.com:30000", "tld": "co.jp"},
	"belgium":    {"sub": "be", "host": "smartproxy.com:40000", "tld": "be"},
	"spain":      {"sub": "es", "host": "smartproxy.com:10000", "tld": "es"},
	"portugal":   {"sub": "pt", "host": "smartproxy.com:20000", "tld": "pt"},
	"greece":     {"sub": "gr", "host": "smartproxy.com:30000", "tld": "gr"},
	"peru":       {"sub": "pe", "host": "smartproxy.com:40000", "tld": "com.pe"},
	"argentina":  {"sub": "ar", "host": "smartproxy.com:10000", "tld": "com.ar"},
	"sweden":     {"sub": "se", "host": "smartproxy.com:20000", "tld": "se"},
	"azerbaijan": {"sub": "az", "host": "smartproxy.com:30000", "tld": "az"},
	"ukraine":    {"sub": "ua", "host": "smartproxy.com:40000", "tld": "com.ua"},
	"hong kong":  {"sub": "hk", "host": "smartproxy.com:10000", "tld": "com.hk"},
	"germany":    {"sub": "de", "host": "smartproxy.com:20000", "tld": "de"},
	"iran":       {"sub": "ir", "host": "smartproxy.com:30000", "tld": "com"},
	"south africa": {
		"sub":  "za",
		"host": "smartproxy.com:40000",
		"tld":  "co.za",
	},
	"south korea": {
		"sub":  "kr",
		"host": "smartproxy.com:10000",
		"tld":  "co.kr",
	},
	"ecuador":   {"sub": "ec", "host": "smartproxy.com:20000", "tld": "com.ec"},
	"chile":     {"sub": "cl", "host": "smartproxy.com:30000", "tld": "cl"},
	"russia":    {"sub": "ru", "host": "smartproxy.com:40000", "tld": "ru"},
	"indonesia": {"sub": "id", "host": "smartproxy.com:10000", "tld": "co.id"},
	"egypt":     {"sub": "eg", "host": "smartproxy.com:20000", "tld": "com.eg"},
	"china":     {"sub": "cn", "host": "smartproxy.com:30000", "tld": "com"},
	"united kingdom": {
		"sub":  "gb",
		"host": "smartproxy.com:30000",
		"tld":  "co.uk",
	},
	"netherlands":   {"sub": "nl", "host": "smartproxy.com:10000", "tld": "nl"},
	"italy":         {"sub": "it", "host": "smartproxy.com:20000", "tld": "it"},
	"australia":     {"sub": "au", "host": "smartproxy.com:30000", "tld": "com.au"},
	"kazakhstan":    {"sub": "kz", "host": "smartproxy.com:40000", "tld": "kz"},
	"singapore":     {"sub": "sg", "host": "smartproxy.com:10000", "tld": "com.sg"},
	"mexico":        {"sub": "mx", "host": "smartproxy.com:20000", "tld": "com.mx"},
	"thailand":      {"sub": "th", "host": "smartproxy.com:30000", "tld": "co.th"},
	"turkey":        {"sub": "tr", "host": "smartproxy.com:40000", "tld": "com.tr"},
	"brazil":        {"sub": "br", "host": "smartproxy.com:10000", "tld": "com.br"},
	"poland":        {"sub": "pl", "host": "smartproxy.com:20000", "tld": "pl"},
	"colombia":      {"sub": "co", "host": "smartproxy.com:30000", "tld": "com.co"},
	"france":        {"sub": "fr", "host": "smartproxy.com:40000", "tld": "fr"},
	"pakistan":      {"sub": "pk", "host": "smartproxy.com:10000", "tld": "com.pk"},
	"canada":        {"sub": "ca", "host": "smartproxy.com:20000", "tld": "ca"},
	"israel":        {"sub": "il", "host": "smartproxy.com:30000", "tld": "co.il"},
	"morocco":       {"sub": "ma", "host": "smartproxy.com:40000", "tld": "co.ma"},
	"mozambique":    {"sub": "mz", "host": "smartproxy.com:41000", "tld": "com"},
	"nigeria":       {"sub": "ng", "host": "smartproxy.com:42000", "tld": "com"},
	"ghana":         {"sub": "gh", "host": "smartproxy.com:43000", "tld": "com"},
	"côte d'ivoire": {"sub": "ci", "host": "smartproxy.com:44000", "tld": "ci"},
	"kenya":         {"sub": "ke", "host": "smartproxy.com:45000", "tld": "co.ke"},
	"liberia":       {"sub": "lr", "host": "smartproxy.com:46000", "tld": "li"},
	"madagascar":    {"sub": "mg", "host": "smartproxy.com:47000", "tld": "com"},
	"mali":          {"sub": "ml", "host": "smartproxy.com:48000", "tld": "com"},
	"malta":         {"sub": "mt", "host": "smartproxy.com:49000", "tld": "com.mt"},
	"monaco":        {"sub": "mc", "host": "smartproxy.com:10000", "tld": "com"},
	"moldova":       {"sub": "md", "host": "smartproxy.com:11000", "tld": "md"},
	"montenegro":    {"sub": "me", "host": "smartproxy.com:12000", "tld": "com"},
	"norway":        {"sub": "no", "host": "smartproxy.com:13000", "tld": "no"},
	"paraguay":      {"sub": "py", "host": "smartproxy.com:14000", "tld": "com.py"},
	"uruguay":       {"sub": "uy", "host": "smartproxy.com:15000", "tld": "com.uy"},
	"venezuela":     {"sub": "ve", "host": "smartproxy.com:16000", "tld": "co.ve"},
	"dominica":      {"sub": "dm", "host": "smartproxy.com:17000", "tld": "dm"},
	"haiti":         {"sub": "ht", "host": "smartproxy.com:18000", "tld": "ht"},
	"honduras":      {"sub": "hn", "host": "smartproxy.com:19000", "tld": "hn"},
	"jamaica":       {"sub": "jm", "host": "smartproxy.com:20000", "tld": "com.jm"},
	"aruba":         {"sub": "aw", "host": "smartproxy.com:21000", "tld": "com"},
	"latvia":        {"sub": "lv", "host": "smartproxy.com:22000", "tld": "lv"},
	"liechtenstein": {"sub": "li", "host": "smartproxy.com:23000", "tld": "li"},
	"lithuania":     {"sub": "lt", "host": "smartproxy.com:24000", "tld": "lt"},
	"luxembourg":    {"sub": "lu", "host": "smartproxy.com:25000", "tld": "lu"},
	"jordan":        {"sub": "jo", "host": "smartproxy.com:26000", "tld": "jo"},
	"lebanon":       {"sub": "lb", "host": "smartproxy.com:27000", "tld": "com"},
	"maldives":      {"sub": "mv", "host": "smartproxy.com:28000", "tld": "com"},
	"mongolia":      {"sub": "mn", "host": "smartproxy.com:29000", "tld": "mn"},
	"oman":          {"sub": "om", "host": "smartproxy.com:30000", "tld": "com.om"},
	"sudan":         {"sub": "sd", "host": "smartproxy.com:31000", "tld": "com"},
	"togo":          {"sub": "tg", "host": "smartproxy.com:32000", "tld": "com"},
	"tunisia":       {"sub": "tn", "host": "smartproxy.com:33000", "tld": "com"},
	"uganda":        {"sub": "ug", "host": "smartproxy.com:34000", "tld": "co.ug"},
	"zambia":        {"sub": "zm", "host": "smartproxy.com:35000", "tld": "co.zm"},
	"afghanistan": {
		"sub":  "af",
		"host": "smartproxy.com:36000",
		"tld":  "com.af",
	},
	"bahrain": {"sub": "bh", "host": "smartproxy.com:37000", "tld": "com"},
	"fiji":    {"sub": "fj", "host": "smartproxy.com:38000", "tld": "com.fj"},
	"new zealand": {
		"sub":  "nz",
		"host": "smartproxy.com:39000",
		"tld":  "co.nz",
	},
	"bolivia": {"sub": "bo", "host": "smartproxy.com:40000", "tld": "com.bo"},
	"bangladesh": {
		"sub":  "bd",
		"host": "smartproxy.com:41000",
		"tld":  "com.bd",
	},
	"armenia":     {"sub": "am", "host": "smartproxy.com:42000", "tld": "am"},
	"georgia":     {"sub": "ge", "host": "smartproxy.com:43000", "tld": "com"},
	"iraq":        {"sub": "iq", "host": "smartproxy.com:44000", "tld": "com"},
	"bhutan":      {"sub": "bt", "host": "smartproxy.com:45000", "tld": "com"},
	"myanmar":     {"sub": "mm", "host": "smartproxy.com:46000", "tld": "com"},
	"cambodia":    {"sub": "kh", "host": "smartproxy.com:47000", "tld": "com"},
	"cyprus":      {"sub": "cy", "host": "smartproxy.com:48000", "tld": "com"},
	"senegal":     {"sub": "sn", "host": "smartproxy.com:49000", "tld": "sn"},
	"seychelles":  {"sub": "sc", "host": "smartproxy.com:10000", "tld": "sc"},
	"zimbabwe":    {"sub": "zw", "host": "smartproxy.com:11000", "tld": "com"},
	"south sudan": {"sub": "ss", "host": "smartproxy.com:12000", "tld": "com"},
	"romania":     {"sub": "ro", "host": "smartproxy.com:13000", "tld": "ro"},
	"serbia":      {"sub": "rs", "host": "smartproxy.com:14000", "tld": "com"},
	"slovakia":    {"sub": "sk", "host": "smartproxy.com:15000", "tld": "sk"},
	"slovenia":    {"sub": "si", "host": "smartproxy.com:16000", "tld": "si"},
	"bahamas":     {"sub": "bs", "host": "smartproxy.com:17000", "tld": "bs"},
	"belize":      {"sub": "bz", "host": "smartproxy.com:18000", "tld": "com.bz"},
	"british virgin islands": {
		"sub":  "vg",
		"host": "smartproxy.com:19000",
		"tld":  "vg",
	},
	"panama": {"sub": "pa", "host": "smartproxy.com:20000", "tld": "com.pa"},
	"puerto rico": {
		"sub":  "pr",
		"host": "smartproxy.com:21000",
		"tld":  "com.pr",
	},
	"trinidad and tobago": {
		"sub":  "tt",
		"host": "smartproxy.com:22000",
		"tld":  "tt",
	},
	"iceland": {"sub": "is", "host": "smartproxy.com:23000", "tld": "is"},
	"ireland": {"sub": "ie", "host": "smartproxy.com:24000", "tld": "ie"},
	"czech republic": {
		"sub":  "cz",
		"host": "smartproxy.com:26000",
		"tld":  "cz",
	},
	"denmark":     {"sub": "dk", "host": "smartproxy.com:27000", "tld": "dk"},
	"estonia":     {"sub": "ee", "host": "smartproxy.com:28000", "tld": "ee"},
	"switzerland": {"sub": "ch", "host": "smartproxy.com:29000", "tld": "ch"},
	"macedonia":   {"sub": "mk", "host": "smartproxy.com:30000", "tld": "com"},
	"costa rica":  {"sub": "cr", "host": "smartproxy.com:31000", "tld": "co.cr"},
	"cuba":        {"sub": "cu", "host": "smartproxy.com:32000", "tld": "com.cu"},
	"albania":     {"sub": "al", "host": "smartproxy.com:33000", "tld": "com"},
	"andorra":     {"sub": "ad", "host": "smartproxy.com:34000", "tld": "com"},
	"austria":     {"sub": "at", "host": "smartproxy.com:35000", "tld": "at"},
	"bosnia and herzegovina": {
		"sub":  "ba",
		"host": "smartproxy.com:37000",
		"tld":  "ba",
	},
	"bulgaria": {"sub": "bg", "host": "smartproxy.com:38000", "tld": "bg"},
	"belarus":  {"sub": "by", "host": "smartproxy.com:39000", "tld": "com"},
	"croatia":  {"sub": "hr", "host": "smartproxy.com:40000", "tld": "hr"},
	"finland":  {"sub": "fi", "host": "smartproxy.com:41000", "tld": "fi"},
	"hungary":  {"sub": "hu", "host": "smartproxy.com:43000", "tld": "hu"},
	"qatar":    {"sub": "qa", "host": "smartproxy.com:44000", "tld": "com.qa"},
	"saudi arabia": {
		"sub":  "sa",
		"host": "smartproxy.com:45000",
		"tld":  "com.sa",
	},
	"vietnam":      {"sub": "vn", "host": "smartproxy.com:46000", "tld": "com.vn"},
	"turkmenistan": {"sub": "tm", "host": "smartproxy.com:47000", "tld": "tm"},
	"uzbekistan":   {"sub": "uz", "host": "smartproxy.com:48000", "tld": "uz"},
	"yemen":        {"sub": "ye", "host": "smartproxy.com:49000", "tld": "com"},
	"central african republic": {
		"sub":  "cf",
		"host": "smartproxy.com:10000",
		"tld":  "com",
	},
	"chad":       {"sub": "td", "host": "smartproxy.com:11000", "tld": "com"},
	"benin":      {"sub": "bj", "host": "smartproxy.com:12000", "tld": "com"},
	"ethiopia":   {"sub": "et", "host": "smartproxy.com:13000", "tld": "com.et"},
	"djibouti":   {"sub": "dj", "host": "smartproxy.com:14000", "tld": "dj"},
	"gambia":     {"sub": "gm", "host": "smartproxy.com:15000", "tld": "gm"},
	"mauritania": {"sub": "mr", "host": "smartproxy.com:16000", "tld": "com"},
	"mauritius":  {"sub": "mu", "host": "smartproxy.com:17000", "tld": "mu"},
	"angola":     {"sub": "ao", "host": "smartproxy.com:18000", "tld": "com"},
	"cameroon":   {"sub": "cm", "host": "smartproxy.com:19000", "tld": "com"},
	"syria":      {"sub": "sy", "host": "smartproxy.com:20000", "tld": "com"},
	"new york":   {"sub": "city", "host": "smartproxy.com:21000", "tld": "com"},
	"los angeles": {
		"sub":  "city",
		"host": "smartproxy.com:21050",
		"tld":  "com",
	},
	"Chicago": {"sub": "city", "host": "smartproxy.com:21100", "tld": "com"},
	"Houston": {"sub": "city", "host": "smartproxy.com:21150", "tld": "com"},
	"Miami":   {"sub": "city", "host": "smartproxy.com:21200", "tld": "com"},
	"London":  {"sub": "city", "host": "smartproxy.com:21250", "tld": "com"},
	"Berlin":  {"sub": "city", "host": "smartproxy.com:21300", "tld": "com"},
	"Moscow":  {"sub": "city", "host": "smartproxy.com:21350", "tld": "com"},
}
